- title: Journal Reviewer
  items:
    - "Journal of Computerized Adaptive Testing (2025)"
    - "Psychometrika (2025, 2026)"
- title: Conference Reviewer
  items:
    - name: "2027 National Council on Measurement in Education (NCME) Annual Meeting"
      subitems:
        - "Individual Paper Proposal Review: Computer Adaptive Testing (3 proposals)"
        - "Individual Paper Proposal Review: Practical Issues in Testing and Assessment (4 proposals)"
        - "Individual Paper Proposal Review: Test Security (3 proposals)"
    - name: "2027 American Educational Research Association (AERA) Annual Meeting"
      subitems:
        - "SIG-Computer and Internet Applications in Education (SIG 22) Proposal Review (3 proposals)"
    - name: "2026 NCME Artificial Intelligence in Measurement and Education Conference (AIME–Con)"
      subitems:
        - "AIME-Con Paper/Poster Session Review Module (5 proposals)"
        - "AIME-Con Innovation Demonstration Review Module (2 proposals)"
